### ISSUE TITLE
release 3 bridges->delchannel

### ISSUE THREAD

**Issue by mark-ingles** [greenfieldtech-nirs/phpari#33]
Hi,
in release-3/src/interfaces/bridges.php line 280, inside the function delchannel, this line:
 $result = $this->pestObject->delete($uri, $delObj);

should be 
 $result = $this->pestObject->post($uri, $delObj);

The HTTP method should be post, not delete. Or else ARI will return "Invalid method"
This error is in the prior versions too.

Reference: https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+Bridges+REST+API#Asterisk13BridgesRESTAPI-removeChannel

Thanks - Mark Ingles

**Comment by greenfieldtech-nirs** [comment]
Hi Mark,

  thanks for the heads up - issue resolved in release 3, please pull again.


Kind Regards,

  Nir Simionovich

  GreenfieldTech

  (schedule) http://nirsimionovich.appointy.com/

  (w) http://www.greenfieldtech.net

  (p) +972-73-2557799        (MSN): nirs@greenfieldtech.net

  (m) +972-54-6982826      (GTALK): nir.simionovich@gmail.com

  (f) +972-73-2557202      (SKYPE): greenfieldtech.nir


----------------------------------------------------------

      Need Storage? <https://copy.com?r=uQUfwT> | Zero Your Inbox
<https://mailstrom.co/referral/ARZJE> | Cloud Servers
<https://www.digitalocean.com/?refcode=97eeea09917a>

----------------------------------------------------------

  *Disclaimer:*

This e-mail is intended solely for the person to whom it is addressed and
may contain confidential or legally privileged information. Access to this
e-mail by anyone else is unauthorized. If an addressing or transmission
error has misdirected this e-mail, please notify the author by replying to
this e-mail and destroy this e-mail and any attachments.
E-mail may be susceptible to data corruption, interception, unauthorized
amendment, viruses and delays or the consequences thereof. If you are not
the intended recipient, be advised that you have received this email in
error and that any use, dissemination, forwarding, printing or copying of
this email is strictly prohibited.
