### ISSUE TITLE
recordings interface, unmute

### ISSUE THREAD

**Issue by mark-ingles** [greenfieldtech-nirs/phpari#34]
phpari/src/interfaces/recordings.php
in function live, line 199, the "unmute" case
$result = $this->pestObject->post($uri);

should be 
$result = $this->pestObject->delete($uri);

Reference: https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+Recordings+REST+API#Asterisk13RecordingsRESTAPI-unmute

Thanks,
Mark Ingles

**Comment by greenfieldtech-nirs** [comment]
Resolved in Release-3 and Master

**Comment by mark-ingles** [comment]
Do you want changes to master that have been fixed in release-3? 
I've just let those go assuming release-3 is going to be master real-soon-now?

**Comment by greenfieldtech-nirs** [comment]
Release-3 has been merged back into Master. There is also a 0.3 release, which is basically Release-3.
