### ISSUE TITLE
ChannelOriginate.php don't work fine

### ISSUE THREAD

**Issue by oscaroxy** [greenfieldtech-nirs/phpari#37]
Hi, I’m trying you library, it’s good, but your example “ChannelOriginate.php” don’t work fine.

I obtain this:

Notice: Array to string conversion in /var/www/workspace_softeoscar/asterisk/phpari/src/interfaces/channels.php on line 150
Error: { “message”: “Application or extension must be specified” } Trace: #0 /var/www/workspace_softeoscar/asterisk/phpari/vendor/educoder/pest/Pest.php(242): Pest->checkLastResponseForError() #1 /var/www/workspace_softeoscar/asterisk/phpari/vendor/educoder/pest/Pest.php(364): Pest->doRequest(Resource id #61) #2 /var/www/workspace_softeoscar/asterisk/phpari/vendor/educoder/pest/PestJSON.php(47): Pest->post(‘/channels/Array’, ‘{“endpoint”:”SI…’, Array) #3 /var/www/workspace_softeoscar/asterisk/phpari/src/interfaces/channels.php(152): PestJSON->post(‘/channels/Array’, Array) #4 /var/www/workspace_softeoscar/asterisk/phpari/src/interfaces/channels.php(178): channels->originate(‘SIP/201′, Array, Array, NULL) #5 /var/www/workspace_softeoscar/asterisk/phpari/examples/ChannelOriginate.php(46): channels->channel_originate(‘SIP/201′, Array, Array) #6 {main}

I print $uri in in line 150, it’s:

/channels/Array

thanks

**Comment by greenfieldtech-nirs** [comment]
Hi There,

Please run a fresh pull. This example is kind'a old and doesn't take into account the channel ID parameter, which was introduced slightly later on in the code. 

Nir

**Comment by greenfieldtech-nirs** [comment]
Closed due to lack of update from the reporting developer
