### ISSUE TITLE
Stop Recording has syntax error

### ISSUE THREAD

**Issue by PadreMontoya** [greenfieldtech-nirs/phpari#39]
When trying to call `recordings()->live('stop', $recording)`, you'll receive the error:

```
Missing argument 2 for PestJSON::post(), called in vendor\/greenfieldtech-nirs\/phpari\/src\/interfaces\/recordings.php on line 180 and defined
```

I fixed it locally by adding `[]` as a second parameter on line 180.  Might also happen with other post() methods that don't require data.

**Comment by greenfieldtech-nirs** [comment]
Issue has been resolved in "develop" branch.
