### ISSUE TITLE
detect fax in ARI

### ISSUE THREAD

**Issue by oscaroxy** [greenfieldtech-nirs/phpari#40]
hi, exist a way in ARI for detect if a channel (outgoing) is a fax?

That is my goal:
I would to call a number, when I receive stasisStart event if it's a voice then I create a bridge, create a new channel (I call a my agent) and add the 2 channel in the bridge, so the 2 channels talks. 
If it's a fax then I would store this info in my DB and hungup the channel, without create bridge and new channel.

exist a StasisFax Event?

How could I do?
thanks

**Comment by greenfieldtech-nirs** [comment]
This is not related to ARI, but more to how Asterisk would detect the channel itself. Technically speaking, Asterisk will perform fax detection, when using SIP for example, using CNG or T.38. Now, what you need to do is something a little different, your dialplan should allow Asterisk to detect the fax answering the remote side - for example, dialing out via originate, put the call into a small Wait of 2 seconds, then, if a fax is detected, you would direct the call flow to a fax extension. If not, direct to your Stasis application.

Stasis and ARI are primarily used for Call Control and Call Flow manipulation, I don't believe that fax detection should be a part of it, as it is performed at a lower level of the Asterisk channel.
