### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by multicore-association** [greenfieldtech-nirs/phpari#46]
I get a connection refused when I try to connect, I am a little confused as to what user-id/password to put in phpari.ini?
  [asterisk_ari]
  username=ariuser
  password=xxxx

where is this user-id/password defined? I tried using the one in ari.conf but it did not work:
  [ariuser]
  type=user
  read_only=no
  password=xxx

Thank you for your help

Michel.

**Comment by greenfieldtech-nirs** [comment]
Hi Michael,

  Affectively, you need to defined the ARI username/password, as defined in `/etc/asterisk/ari.conf` in the phpari.ini file.

  So, for example, if your `/etc/asterisk/ari.conf` looks like this:

`
[general]
enabled = yes          
pretty = yes           
 
[asterisk]
type = user
read_only = no
password = asterisk
`

  Then, your phpari.ini file should look like this:
`
[general]
debug=0
logfile=console ; console for direct console output, filename for file based logging

[asterisk_ari]
username=asterisk
password=asterisk
host=localhost
port=8088
endpoint=/ari
transport=ws ; ws for none encrypted, wss for encrypted (currently, only ws is supported)

[asterisk_manager]
username=amiuser
password=amipassword
host=127.0.0.1
port=5038
`

Hope this clarifies things.

**Comment by multicore-association** [comment]
thank you for the clarification, I was able to connect.
