### ISSUE TITLE
Connecting 2 incoming channels

### ISSUE THREAD

**Issue by apocsrbs** [greenfieldtech-nirs/phpari#61]
I've been pondering over this. Is it possible to connect 2 channels from 2 bridges?

Much like a callcenter would do. If A calls you (B) and you put A on hold while you call C and then you'll want to connect A to C and leave the conversation.

**Comment by 91Abdullah** [comment]
Yes it is possible you need to:
1. Create a bridge
2. Add channel A to bridge
3. Add channel B to bridge

**Comment by apocsrbs** [comment]
Hi @91Abdullah - Thank you for your reply! :)

Issue is, with my setup, that the call goes to a webRTC browser and i'm having difficulties following the channels and the methods to attach the correct channels :)

**Comment by apocsrbs** [comment]
This issue has been resolved using the js rtc framework.
